#ifndef SYNTAX_TAB_H
#define SYNTAX_TAB_H


#define DEBUT 
#define EXECUTION 
#define FIN 
#define NUM 
#define REAL 
#define SI 
#define ALORS 
#define TEXT 
#define ELSE 
#define TANTQUE 
#define FAIRE 
#define ET_LOGIQUE 
#define OU_LOGIQUE 
#define NEGATION 
#define FIXE 
#define AFFICHE 
#define LIRE 
#define EGAL 
#define DIFFERENT 
#define ASSIGNATION 
#define SUPERIEUR 
#define SUP_EGAL 
#define INFERIEUR 
#define INF_EGAL
#define AFFECTATION 
#define PLUS 
#define MOINS
#define FOIS 
#define DIVISER 
#define POINT_VIRGULE 
#define DEUX_POINTS 
#define VIRGULE 
#define PARENTHESE_OUVRANTE 
#define PARENTHESE_FERMANTE 
#define CROCHET_OUVRANT 
#define CROCHET_FERMANT 
#define GUILLEMENT 
#define ACCOLADE_OUVRANTE 
#define ACCOLADE_FERMANTE 
#define ID 
#define CST
#define DOUBLE_SHARP
#define STRING
#define POINT
//caractere specieux
#define E_ACUTE 
#define E_GRAVE 
#define E_CIRCUMFLEX 
#define A_GRAVE 
#define U_GRAVE 
#define C_CEDILLA 
#define O_CIRCUMFLEX 
#define A_CIRCUMFLEX 
#define I_CIRCUMFLEX 
#endif
